kind: Service                             
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  ports:
    - port: 8080      #container                         
      targetPort: 80  #pods port                  
      nodePort: 31200  
  selector:
    app: mrdevops                    
  type: LoadBalancer                   
